version: '3'

services:
    gomdb:
      image: mongo:latest
      container_name: gomdb
      # restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword

      ports:
        - "27017:27017"
      volumes:
        - mdbdata:/data/db
    goapp:
      image: gowebapp:latest
      container_name: localapp
      depends_on:
        - "gomdb"
      #restart: always
      links:
        - "gomdb"
      build:
        context: .
        dockerfile: "Dockerfile.goapp"

      ports:
        - "8080:8080"
volumes:
    mdbdata:
