version: '3'

services:
    mdb:
      image: mongo:latest
      container_name: gomdb
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword

      ports:
        - "27018:27017"
      volumes:
        - mdbdata:/data/db
    #goapp:
     # image: gowebapp:latest
      #container_name: localapp
      #restart: always
      #links:
      #  - gomdb
      #build:
      #  context: .
      #  dockerfile: Dockerfile.goapp

      #ports:
      #  - "8080:8080"
volumes:
    mdbdata:
